version: "2"
services:
    databases:
        image: database
       
        networks:
            - wheel
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=EasvEasv123!
            - MSSQL_PID=Express
            - MSSQL_DATABASE=CollectionsDB
        
    API:
        image: ckbackend
        networks:
            - wheel
        ports:
            - '5001:80'
        depends_on:
            - databases
    flyway:    
        image: flyway/flyway:latest
        networks: 
            - wheel
        command: ["migrate"]
        volumes:
            - ./db:/flyway/sql
            - ./db:/flyway/conf
        depends_on:
            - databases
networks:
    wheel: 
        driver: bridge