version: "2"
services:
    databases:
        image: database
       
        networks:
            - wheel
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=EasvEasv123!
            - MSSQL_PID=Express
            - MSSQL_DATABASE=CollectionsDB
        
    API:
        image: ckbackend
        networks:
            - wheel
        ports:
            - '5001:80'
        depends_on:
            - databases
    flyway:    
        image: flyway/flyway:latest
        networks: 
            - wheel
        command: ["migrate"]
        volumes:
            - ./db:/flyway/sql
            - ./db:/flyway/conf
        depends_on:
            - databases
    
    kib01:
        image: docker.elastic.co/kibana/kibana:7.9.0
        container_name: kb01
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: http://es01:9200
        networks:
            - wheel
        depends_on:
            - API

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xm512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - wheel
        depends_on:
            - API
networks:
    wheel: 
        driver: bridge