version: "2"
services:
    databases:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        networks:
            - wheel
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=EasvEasv123!
            - MSSQL_PID=Express
    API:
        image: ckbackend
        networks:
            - wheel
        ports:
            - '5001:80'
        depends_on:
            - databases
    flyway:
        image: flyway/flyway:latest
        command: ["migrate"]
        volumes:
            - ./sql:/flyway/sql
            - ./conf:/flyway/conf
        depends_on:
            - databases
networks:
    wheel: 
        driver: bridge